<a href="https://colab.research.google.com/github/miguelangel18241/hackerrank/blob/main/diagonalDifference.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Generate a 3x3 matrix filled with random integers between 0 and 9
random_matrix = np.random.randint(10, size=(3, 3))

print(random_matrix)

[[4 4 0]
 [6 3 5]
 [5 1 1]]


In [23]:
def diagonalDifference(x):
  sum_lef_to_right = 0
  sum_right_to_left = 0
  for i in range(len(x)):
    sum_lef_to_right += x[i][i]
    sum_right_to_left += x[i][len(x)-1-i]
  absolute_difference = abs(sum_lef_to_right - sum_right_to_left)
  return absolute_difference


# Generate a 3x3 matrix filled with random integers between 0 and 9
random_matrix = np.random.randint(10, size=(3, 3))

print(random_matrix)

diagonalDifference(random_matrix)

[[5 2 4]
 [9 8 7]
 [1 5 5]]


5